#!/bin/bash
LOCAL_DIR=`pwd`
if [[ ${LOCAL_DIR} == ${HOME} ]]
then
  echo "You shouldn't sync from home"
  exit 2
fi
REMOTE_DIR=`cd ..; pwd`
REMOTE_DIR=${REMOTE_DIR/dropbox/workspace}
cd $LOCAL_DIR
rsync -auvW --inplace $LOCAL_DIR $1:$REMOTE_DIR
